//src/constants/permissions.js
export const PERMISSIONS = {
  // Plataforma
  TENANT_VIEW: 'TENANT_VIEW',
  TENANT_CREATE: 'TENANT_CREATE',
  TENANT_EDIT: 'TENANT_EDIT',
  TENANT_PAUSE: 'TENANT_PAUSE',

  PLAN_VIEW: 'PLAN_VIEW',
  PLAN_EDIT: 'PLAN_EDIT',

  // Tenant
  APPOINTMENT_VIEW: 'APPOINTMENT_VIEW',
  APPOINTMENT_CREATE: 'APPOINTMENT_CREATE',
  APPOINTMENT_EDIT: 'APPOINTMENT_EDIT',

  CLIENT_VIEW: 'CLIENT_VIEW',
  CLIENT_CREATE: 'CLIENT_CREATE',
  CLIENT_EDIT: 'CLIENT_EDIT',

  SERVICE_VIEW: 'SERVICE_CREATE',
  SERVICE_VIEW: 'SERVICE_VIEW',
  SERVICE_EDIT: 'SERVICE_EDIT',

  USER_VIEW: 'USER_VIEW',
  USER_EDIT: 'USER_EDIT',

  // Dashboard
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
}